name: Publish package to NPM
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_PAT }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.18.0"
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Configure git bot
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@84145992+ektadubey3@users.noreply.github.com"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_KEY }}

      - name: Typecheck
        run: pnpm typecheck

      - name: Build Library
        run: pnpm build

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Auto Increment Version
        run: |
          pnpm version patch -m "chore(release): bump version to %s [skip ci]"

      - name: Push Version Update to GitHub
        run: |
          git fetch origin master
          git rebase origin/master
          git push origin master --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_KEY }}
